name: 'Run Tests: Timer'

on:
  pull_request:
  push:

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

      - name: Run Jest Tests
        run: yarn jest

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5
        if: github.branch == 'master'
        with:
          build: yarn build
          start: yarn preview
          install: false

      # Notify Status

      - name: Telegram Notify - Success
        uses: appleboy/telegram-action@master
        if: ${{ success() }}
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Todos os testes relacionados ao ${{ github.event_name }} passaram!
            Repositório: ${{ github.repository }}

      - name: Telegram Notify - Failure
        uses: appleboy/telegram-action@master
        if: ${{ failure() }}
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Foram econtrados problemas nos testes do ${{ github.event_name }}.
            Repositório: ${{ github.repository }}
